server:
  port: 20081


spring:
  application:
    name: user-service

    cloud:
      nacos:
        discovery:
          server-addr=localhost:8848: #nacos服务中心地址

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_project_iam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456


#暴露全部监控端点
management.endpoints.web.exposure.include: '*'


# 自定义注解配置
hello:
  name: xiaoming
  address: beijing

## mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath*:/com/genlian/server/service/**/mapper/xml/*.xml
#  typeEnumsPackage: com.genlian.server.enums.*
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    mapUnderscoreToCamelCase: true # 是否开启自动驼峰命名规则（camel case）映射
#    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID # 自动分配（雪花算法）
#      db-column-underline: true #驼峰下划线转换
#      update-strategy: ignored


#    配置ribbon
stu-provide:
  ribbon:

    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数

