server:
  port: 20081

spring:
  application:
    name: user-service

    cloud:
      nacos:
        discovery:
          server-addr=localhost:8848: #nacos服务中心地址

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_project_iam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456


#暴露全部监控端点
management.endpoints.web.exposure.include: '*'


# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/com/genlian/server/service/**/mapper/xml/*.xml
  typeEnumsPackage: com.genlian.server.enums.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true # 是否开启自动驼峰命名规则（camel case）映射
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      id-type: ASSIGN_ID # 自动分配（雪花算法）
      db-column-underline: true #驼峰下划线转换
      update-strategy: ignored

