server:
  port: 20082

spring:
  application:
    name: order-service

    cloud:
      nacos:
        discovery:
          server-addr=localhost:8848: #nacos服务中心地址

    datasource:
      url: jdbc:mysql://127.0.0.1:3306/my_project_iam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

#暴露全部监控端点
management.endpoints.web.exposure.include: '*'